import type { Metadata } from "next";
// @ts-ignore: Allow global CSS side-effect import without a declaration file
import "./globals.css";
import VisualEditsMessenger from "../visual-edits/VisualEditsMessenger";
import ErrorReporter from "@/components/ErrorReporter";
import Script from "next/script";
import AccessibilityProvider from "@/components/AccessibilityProvider";
import Header from "@/components/Header";
import { Toaster } from "@/components/ui/sonner";
import ThreeBackground from "@/components/ThreeBackground";

export const metadata: Metadata = {
  title: "Samavesh",
  description: "Generated by Team Codeucate",
  icons: {
    icon: "/logo.png",
    shortcut: "/logo.png",
    apple: "/logo.png",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="antialiased">
        <ErrorReporter />
        <Script
          src="https://slelguoygbfzlpylpxfs.supabase.co/storage/v1/object/public/scripts//route-messenger.js"
          strategy="afterInteractive"
          data-target-origin="*"
          data-message-type="ROUTE_CHANGE"
          data-include-search-params="true"
          data-only-in-iframe="true"
          data-debug="true"
          data-custom-data='{"appName": "YourApp", "version": "1.0.0", "greeting": "hi"}'
        />
        <AccessibilityProvider>
          <ThreeBackground />
          <Header />
          {children}
        </AccessibilityProvider>
        <Toaster richColors closeButton />
        <VisualEditsMessenger />
      </body>
    </html>
  );
}
